apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description:  demo-api
  tags:
    - demo
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
  